//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ABC
    {
        public decimal ID { get; set; }
        public  string BRAND { get; set; }
        public  string CAREGORY { get; set; }
        public Nullable<decimal> STOCK { get; set; }
        public string USERNAME { get; set; }
        public System.DateTime DATETIME { get; set; }
    }
}
